@echo off

::set /p image="chemin vers l'image ? : "
::/Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py/Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model model\parking_non_parking_test.model	--image ..\examples\image.png
::_____________________________parking_____________________________________________
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/parking/  --image output_1.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 

::__________________________________non_parking_______________________________________
 Users/mosbahhachem/anaconda3/bin/python3 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output1.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output2.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output3.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output4.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output5.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output6.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output7.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output8.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output9.jpg    --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output10.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output11.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output12.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output13.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output14.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output15.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output16.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output17.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/

 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output18.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output19.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output20.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output21.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output22.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output23.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output24.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output25.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output26.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output27.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output28.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output29.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output30.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output31.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output32.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output33.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output34.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/

 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output35.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output36.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output37.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output38.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output39.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output40.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output41.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output42.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output43.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output44.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output45.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output46.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output47.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output48.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output49.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/
    
 /Users/mosbahhachem/Documents/git/StageCerema/code/test_parking.py --model /Users/mosbahhachem/Documents/git/StageCerema/code/model/parking_non_parking_test.model --chemin /Users/mosbahhachem/Documents/git/StageCerema/code/data/test/non_parking/  --image output50.jpg   --result /Users/mosbahhachem/Documents/git/StageCerema/code/data/result/